name: Generat ascii Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout 
      uses: actions/checkout@v4

    - name: List the files
      run: ls -larth 

    - name: Execute shell script
      run: | 
        chmod +x ascii-script.sh
        ./ascii-script.sh
      
    
